### ISSUE TITLE
Home screen

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.noi.community.android#11]
As an App user I want to have a home screen in order to see the main information about the Community and the primary functionalities of the app

**Comment by stezan** [comment]
Hi @Piiit, I have a question about events visualisation on Home screen (in the XD UI the tab name is Today).

Without applying any filter (so let's say in the initial event list situation), which events should we request? Because I noticed that if I pass no additional parameters, the API responds with all the events, also those of 2017.
Should we pass the `startdate` parameter valorised with "today"?

Thanks!
