### ISSUE TITLE
The image sizes/measures in the detail view of single events are wrong

### ISSUE THREAD

**Issue by MarE1991** [noi-techpark/it.bz.noi.community.android#124]
The images I see when opening an event detail page are wrong. Shouldn't they have kind of a 3:2 size or something like that? Now they are all in portrait format and that causes that most of the images and graphics get cut.

- Android Version: 11
- Language of your application: de
- Phone: Samsung Galaxy A40
- Application version (you find it in the `More` section under the NOI logo): 0.1.0.1657010070
![Screenshot_20220706-163351_Community](https://user-images.githubusercontent.com/92152188/177576505-57fdc211-3763-48e9-815f-064e5f66c31f.jpg)
![Screenshot_20220706-163406_Community](https://user-images.githubusercontent.com/92152188/177576517-7b74099a-9409-48c0-ad54-92225b7a7a00.jpg)

**Comment by matax87** [comment]
@MarE1991 we set the wrong size. By design the size must be 315x210 which is indeed a ratio of 3:2. Is it ok? See the attached screenshot

![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-07-07 at 10 13 14](https://user-images.githubusercontent.com/4108197/177726016-8643c01f-990f-488e-ae91-8e8c77beb20a.png)


![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-07-07 at 10 15 13](https://user-images.githubusercontent.com/4108197/177726051-052ef6ae-8329-4de3-bd1b-53d8a4e2fdc6.png)

Thank you!

**Comment by chiaraDimension** [comment]
@MarE1991
I still have to fix the Android version.

**Comment by matax87** [comment]
Please note that on iOS we also have the wrong horizontal spacing between images. I'm going to fix both the issue on iOS and @chiaraDimension is going to fix just the images' size issue on android.

Thank you.

**Comment by MarE1991** [comment]
> @MarE1991 I still have to fix the Android version.

@chiaraDimension ok sorry, I reopened and will check when done also on android. THX
