### ISSUE TITLE
Mapping of API fields to UI

### ISSUE THREAD

**Issue by stezan** [noi-techpark/it.bz.noi.community.android#15]
<img width="350" alt="Screenshot 2021-09-15 at 16 54 07" src="https://user-images.githubusercontent.com/22938515/133457134-b63fb1eb-8e9d-4339-9def-e70726fe0ed5.png">

We would like to confirm the mapping between the fields in the API response and our UI

- Id --> eventId
- Shortname --> title of the event
- EventDescription --> Section about in event details
- EventLocation --> location (basso a sinistra)
- StartDate --> date and time of event start
- EndDate --> date and time of event end
- ImageGallery[0].ImageUrl --> event image (90% of cases ImageGallery array is null so no image is present)

Is this mapping API - UI correct?

**Comment by RudiThoeni** [comment]
- Id --> eventId OK
- Shortname --> title of the event NO, use EventDescriptionDE, EventDescriptionIT, EventDescriptionEN
- EventDescription --> Section about in event details NO, use EventTextDE, EventTextIT, EventTextEN
- StartDate --> date and time of event start  OK
- EndDate --> date and time of event end  OK
- ImageGallery[0].ImageUrl --> event image (90% of cases ImageGallery array is null so no image is present)  OK, yes there are only a few images
- EventLocation --> location (basso a sinistra) --> Here i am not sure what should be displayed and i think this questions have to be defined by the PM group. Looking at the Website i think they use AnchorVenue. Each event has one Anchorvenue. Today.noi.bz.it shows SpaceDesc of every room. What should the app do if there are more different Rooms for an event...... Should the behaviour be like on the Website, if yes i think we simply have to use "AnchorVenue". 


Another Field that is displayed by Today.noi.bz.it and the Website is the Organizer.  not sure if it should be displayed also on the map.
For certain reasons here there is a rule to apply, this rule is
if(Display5 is null or empty)
Organizer --> CompanyName
else
Organizer --> Display5


The filter for the events i think should be
onlyactive = true --> Display only active events
eventlocation = NOI,OUT --> Display only Noi Events and Events Outside Noi techpark (Filter out Eurac events)

**Comment by RudiThoeni** [comment]
ok they said me that only eventlocation=NOI will be shown by NOI App

**Comment by stezan** [comment]
@RudiThoeni on some events `EventDescriptionDE` or `EventDescriptionEN` or `EventDescriptionIT` (that, as you said,  is used as event title) is missing. For example with the URL https://tourism.opendatahub.bz.it/v1/EventShort?onlyactive=true&eventlocation=NOI&pagenumber=1&pagesize=20&startdate=2021-09-20 the first event is

```
"EventDescriptionDE": "TUTORSHIP: EIN INSTRUMENT FÜR DIE WEITERENTWICKLUNG IN DEN PFLEGE-, REHABILITATIONS-, TECHNIK- UND PRÄVENTIONSBERUFE",
"EventDescriptionEN": "",
"EventDescriptionIT": ""
```

What should we do in this case?

**Comment by RudiThoeni** [comment]
i think for the MVP it is enough to have Fallback to EventDescription when one of the language relevant desc is empty........
the problem is in the import of the data from another interface, we have to fix it there...... the app should simply display the language relevant Title, and if it is empty lets add a fallback to the field EventDescription ..........

**Comment by RudiThoeni** [comment]
the event is inserted this way.... from 27.10 14:00 - 29.10 12:00 its 3 days long....
What cards should be created in this case? one for each day?  But this result in a mess, because then we have

day 1 14:00 - 23:59
day 2 00:01 - 23:59
day 3 00:01 - 12:00

today.noi.bz.it uses the "Roombooked" (with a special rule:
`where NOT Comment Like  "x"`
for this reason only this data is shown
`{
Space: "NOIKH",
Comment: "",
EndDate: "2021-10-28T20:30:00",
Subtitle: "",
SpaceDesc: "NOI Crane Hall",
SpaceType: "NO",
StartDate: "2021-10-28T17:00:00",
EndDateUTC: 1635445800000,
SpaceAbbrev: "NOI Crane Hall",
StartDateUTC: 1635433200000,
SpaceDescRoomMapping: "Crane Hall"
}`

Here i see only the possibilities
-do not insert events over more days (make 1 event per day) by the redaction
-Using the Roombooked List to create the cards....

**Comment by MarE1991** [comment]
@Piiit we cannot avoid inserting events that go over more days. So what could be a technically practicable solution? Do I need to involve Studio Hug?

**Comment by RudiThoeni** [comment]
First i think it is better to understand why there are this multiple day events inside.....
I think displaying start date for an event from 00:01 - 23:59 (at example for day 2) does not make sense....... I think there are only a few events that goes over night (Hackathon).

In this case here the event inserted from Eurac Meeting Management is from Event startdate 27.10 - 29.10 Event enddate but only one Room is defined to show from 28.10 17:00 - 18:30. Maybe here we should understand why it is set from 27.10 - 29.10 if no room is used on 27.10 and 29.10. Is it intentional or an error?

One strategy could be to shift to the same Endpoint (Get Event by Rooms) as today.noi.bz.it uses. But this means if Event x has two rooms where it takes place, two event cards are generated?

**Comment by Piiit** [comment]
@matax87 @RudiThoeni @MarE1991 I think this has to be decided internally and with the Event management, and then implemented. We cannot provide a mapping without a final decision on this.
