### ISSUE TITLE
Wrong versionName in Android Application

### ISSUE THREAD

**Issue by stezan** [noi-techpark/it.bz.noi.community.android#71]
Hi @Piiit , me and @chiaraDimension noticed that the **versionName** of the application is incorrect.
The version name should be for example **0.1.0**
The version code should be for example **1635954241**

<img width="1606" alt="Screenshot 2021-11-05 at 09 57 02" src="https://user-images.githubusercontent.com/22938515/140484558-f27cfeeb-bc4a-4c32-a990-805c3160162a.png">
.

You used 1635954241 both for version name and code and this is the result

![Screenshot_20211105-095205](https://user-images.githubusercontent.com/22938515/140484840-f8f1afb5-492e-4ca2-ac51-72958dee37aa.jpeg)

The only value to be automatically incremented is the **versionCode**

**Comment by Piiit** [comment]
@chiaraDimension This was a test to see if the automatic updates arrive to the phones, when the string for versions also change each time... I just attached the versioncode to the version string to test that, to be sure to always have a unique identifier. However, the updates still do not arrive automatically. We need to uninstall and re-install the app, and in addition wait for the update approx 2 days, even if in the console it is immediately available. 

I suggest to remove the concatenation in the UI, so that also the store itself and the installer shows the whole version. Otherwise on my Xiaomi I am not able to see the build number before the installation.

Do you think that could be a solution, or is there some problem I do not see yet?

**Comment by stezan** [comment]
@Piiit 

- Version name: Is the app version visualised by the user on the Google Play Store, it is formed by 3 numbers (x.y.z) where x is the major version, y is the minor version and z identifies the eventual fix released to the user
- Version code: Is an incremental number that is used to differentiate the different builds on the Google Play Console

You can have as many "0.1.0" versions as you want, the important thing is that each one has its own Version Code

Guidelines suggest that is a bad practice changing version name for Internal Testing purpose, you should only change version code.
Version name should change when you deploy a new release in production, incrementing z if it is a fix, incrementing y if is is a little update and incrementing x if there are consistent changes.

So you should only change version code for internal testing releases

**Comment by stezan** [comment]
> Otherwise on my Xiaomi I am not able to see the build number before the installation.

You can install it and then check the build number in the Tab More if you have any doubt

**Comment by Piiit** [comment]
@stezan I revert my changes...

**Comment by Piiit** [comment]
Fixed in https://github.com/noi-techpark/it.bz.noi.community.android/commit/eb3484af1837daf142eedd4078b82a71d56dc112
