### ISSUE TITLE
NOI room booking system

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.noi.community.android#8]
As an app user I want to book rooms or other stuff (e.g. monitors) that I need need.
In the first version of the MVP the app should link the actual booking system:
https://rooms.noi.bz.it/​

**Comment by chiaraDimension** [comment]
@Piiit We have encountered a problem with rooms.noi.bz.it SSL certificate. Could you please check if it is valid? If it is, could you replace it with one that also includes intermediates? As you can see from https://ssltools.godaddy.com/views/certChecker, it seems the problem is that intermediates are missing. Probably the browser can work anyway, instead the app can not retrieve them.

cc @stezan

**Comment by Piiit** [comment]
Please try with https://outlook.com/owa/calendar/NOITechpark1@noi.bz.it/bookings/ in the meantime... I will write to our IT department about the other URL

**Comment by Piiit** [comment]
Please make all the URLs configurable, such that we can immediately find and change them in the source code... thanks

**Comment by chiaraDimension** [comment]
> Please try with https://outlook.com/owa/calendar/NOITechpark1@noi.bz.it/bookings/ in the meantime... I will write to our IT department about the other URL

I already try this url and I confirm you that it works. The problem regards only the certificate of the other one. In the meantime we can use this one.

**Comment by Piiit** [comment]
Thanks @chiaraDimension 

Our IT dept. confirmed that the new certificate due in 2 weeks, will be with intermediates installed.
